Feat/civ 4240 api test sdo dj
hmcts/civil-ccd-definition pull request #1199
Opened 2022-08-29 10:38 UTC by miguelMolina3691

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2022-09-14 09:54 UTC, mounikahmcts requested changes

2022-09-14 09:54 UTC, mounikahmcts commented on e2e/config.js
> +    email: 'judge-civil-02@example.com',
Judge user should be used from ref data users. I do not see judge-civil-02@example.com user on AAT. so the tests never pass

2022-09-22 09:17 UTC, mounikahmcts requested changes

2022-09-22 09:17 UTC, mounikahmcts commented on e2e/config.js
> +    email: process.env.ENVIRONMENT === 'demo' || process.env.ENVIRONMENT ===  'preview'
The condition says if env is preview or demo then user judge-civil-02@example.com.. i think the condiiton should be if env is local use judge-civil-02@example.com and all other envs use 4924246EMP-@ejudiciary.net

2022-10-13 07:05 UTC, hmcts-version1-ignacio approved these changes

2022-10-13 07:59 UTC, merged