CIV-4182 Uplifting Hearing Availability DQ screen SPEC
hmcts/civil-ccd-definition pull request #1486
Opened 2022-10-18 15:08 UTC by LTurkingtonHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-4182

### Change description ###
Uplifting hearing availability screen DQ for small claims and fast track in 1v1 and 1v2 cases. 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-10-18 15:55 UTC, sankaviv1 approved these changes

2022-10-19 09:05 UTC, kurt-uk requested changes

2022-10-19 09:05 UTC, kurt-uk commented on ccd-definition/CaseEventToComplexTypes/DefendantResponseLRspec-base-nonprod.json
> +[
youll need to remove the `who`'s looking at your story, you might need another file structure jig around or if youre using this one as the one for HNL then remove it from here

2022-10-20 11:50 UTC, sankaviv1 submitted a review, later dismissed

2022-10-20 13:10 UTC, kurt-uk approved these changes

2022-11-15 15:08 UTC, sankaviv1 approved these changes

2022-11-15 15:15 UTC, Gareth40343 approved these changes

2022-11-15 18:08 UTC, merged