feat/CIV-2493 sdo api tests
hmcts/civil-ccd-definition pull request #1664
Opened 2022-11-09 09:22 UTC by dtortolaV1

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-2493

### Change description ###
Added SDO API tests

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-11-11 14:46 UTC, m-meulendijks-v1 approved these changes

2022-11-14 22:15 UTC, sampankumar approved these changes

2022-11-15 10:28 UTC, mounikahmcts commented on build.gradle
> +  args = ['PREVIEW']
Why is this needed?

2022-11-15 11:46 UTC, mounikahmcts commented on e2e/tests/api_tests/sdo/sdo_test.js
> +  await api_sdo.unspecifiedProcess(config.applicantSolicitorUser, config.defendantSolicitorUser);
Enable test using legal advisor [tribunal_caseworker_region1@justice.gov.uk](mailto:tribunal_caseworker_region1@justice.gov.uk)/Password12! for central london county court

2022-11-15 11:46 UTC, mounikahmcts requested changes

2022-11-15 11:46 UTC, mounikahmcts commented on e2e/tests/api_tests/sdo/sdo_test.js
> +  await api_sdo.unspecifiedProcess(config.applicantSolicitorUser, config.defendantSolicitorUser);
Enable test using legal advisor [tribunal_caseworker_region1@justice.gov.uk](mailto:tribunal_caseworker_region1@justice.gov.uk)/Password12! for central london county court

2022-12-07 03:06 UTC, closed without merging