Feat/civ 5936 merge hnl dj sdo
hmcts/civil-ccd-definition pull request #1703
Opened 2022-11-16 17:00 UTC by sherlynkhaw

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-5936

### Change description ###

- Removed/renamed SDO-HNL files
- Moved HNL changes into original DJ/SDO files.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-11-22 10:08 UTC, kurt-uk submitted a review, later dismissed

2022-11-22 12:12 UTC, sankaviv1 approved these changes

2022-11-25 13:10 UTC, sherlynkhaw commented on bin/build-release-ccd-definition.sh
>     #excludedFilenamePatterns="-e *-prod.json,*-SDO-nonprod.json,*-base-nonprod.json"
I will remove SDO exclusion from this comment after QA is done

2022-12-07 13:12 UTC, Gareth40343 approved these changes

2022-12-07 14:59 UTC, kurt-uk approved these changes

2023-01-05 10:59 UTC, mounikahmcts requested changes

2023-01-05 10:59 UTC, mounikahmcts commented on e2e/pages/defaultJudgment/requestDefaultJudgmentforUnspecifiedClaims.js
> +      await I.fillField(this.fields.selectOrderAndHearingDetailsForDJTask.hearingTimeOptions.input, 'hearing time');
This will break DJ tests if we enable it on master when DJ goes live

2023-01-18 15:30 UTC, merged