civil-6050-order-event
hmcts/civil-ccd-definition pull request #1794
Opened 2022-12-01 12:36 UTC by nagaraju-deekonda

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-6050

### Change description ###
An event drop-down/trigger named "Generate Directions Order" that starts the journey for a judge to provide/create a judicial order.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-12-01 13:05 UTC, drummondjm approved these changes

2022-12-01 14:30 UTC, hmcts-version1-ignacio approved these changes

2022-12-05 09:24 UTC, drummondjm submitted a review, later dismissed

2022-12-05 09:24 UTC, hmcts-version1-ignacio approved these changes

2023-01-24 10:24 UTC, filippo-possenti-version1 commented on charts/civil-ccd/values.preview.template.yaml
> +        image: 'hmctspublic.azurecr.io/civil/service:pr-1894'
Just marking this as we don't want to merge it to master.

2023-01-24 10:24 UTC, filippo-possenti-version1 requested changes
Marking as "Request changes" to prevent one change to go in by mistake

2023-01-25 17:55 UTC, filippo-possenti-version1 approved these changes

2023-01-25 18:59 UTC, sankhajuria approved these changes

2023-01-25 19:00 UTC, merged