URL changes for self-signed
hmcts/civil-ccd-definition pull request #1939
Opened 2023-01-05 17:31 UTC by m-meulendijks-v1

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-6655

### Change description ###
Changing CCD URLs to match self signed domain.

**Does this PR introduce a breaking change?** (check one with "x")

```
[x] Yes
[ ] No
```

2023-01-09 13:57 UTC, HarryH96 approved these changes

2023-01-09 16:18 UTC, filippo-possenti-version1 approved these changes

2023-01-10 16:49 UTC, filippo-possenti-version1 commented on charts/civil-ccd/values.preview.template.yaml
> +  debug: true
This has been added temporarily. Stopping the merge of this PR through review to ensure this is removed before merging.

2023-01-10 16:49 UTC, filippo-possenti-version1 requested changes
Blocking a merge to ensure that a debug instruction is removed before merging.

2023-01-10 16:55 UTC, closed without merging