Update suppressions.xml
hmcts/civil-ccd-definition pull request #2079
Opened 2023-01-26 09:38 UTC by miguelMolina3691

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-01-27 18:06 UTC, filippo-possenti-version1 requested changes
Rebase this PR.

It's been created from either a branch other than master or an outdated version of master and contains changes that have nothing to do with suppressions and that you haven't done yourself.

If not rebased, we risk deploying changes that are not meant to be deployed.

Ask for my assistance as needed.

2023-01-30 11:24 UTC, filippo-possenti-version1 submitted a review, later dismissed

2023-01-30 11:52 UTC, filippo-possenti-version1 approved these changes

2023-01-30 12:01 UTC, bhagyashreesharma90 approved these changes

2023-01-30 12:02 UTC, maciejmodzelewski approved these changes

2023-01-30 12:40 UTC, merged