CIV-6024 HMC access
hmcts/civil-ccd-definition pull request #2248
Opened 2023-02-22 10:20 UTC by suvarnathekkoot

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-6024

### Change description ###

Access the hearings tab - for EXUI team

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-02-22 15:33 UTC, sankaviv1 requested changes

2023-02-22 15:33 UTC, sankaviv1 commented on ccd-definition/AuthorisationCaseField/AuthorisationCaseField-HMCaccess-nonprod.json
> +    "CaseFieldID": "hearingsTabAccess",
i think exui need to do something for this tab

2023-02-22 15:33 UTC, sankaviv1 commented on ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-HMCaccess-nonprod.json
> +    "CaseEventID": "CREATE_HEARING_ACCESS",
we don't need these events for hearings

2023-02-23 17:18 UTC, maciejmodzelewski approved these changes

2023-05-05 03:01 UTC, closed without merging