CIV-7300 hearing notice bugs
hmcts/civil-ccd-definition pull request #2259
Opened 2023-02-24 09:24 UTC by drummondjm

https://tools.hmcts.net/jira/browse/CIV-7300

Bug fixes for incorrect hearing fee, an documents not showing

Does this PR introduce a breaking change? (check one with "x")

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[c ] No
```

2023-03-06 11:20 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-03-07 10:50 UTC, miguelMolina3691 submitted a review, later dismissed

2023-03-13 17:24 UTC, filippo-possenti-version1 requested changes
Gating to ensure we don't merge with test changes in it.

2023-03-13 17:28 UTC, filippo-possenti-version1 approved these changes

2023-03-14 10:19 UTC, miguelMolina3691 approved these changes

2023-03-15 15:16 UTC, merged