CIV-3420 Manage case flags
hmcts/civil-ccd-definition pull request #2274
Opened 2023-02-28 16:14 UTC by sankaviv1

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-3420

### Change description ###

- add manage case flags event config
- add e2e and api

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-03-02 10:22 UTC, maciejmodzelewski requested changes
There are tests failing in the build for this PR https://build.platform.hmcts.net/blue/organizations/jenkins/HMCTS_a_to_c%2Fcivil-ccd-definition/detail/PR-2274/4/pipeline

2023-03-02 16:45 UTC, Gareth40343 submitted a review, later dismissed

2023-03-02 16:46 UTC, maciejmodzelewski submitted a review, later dismissed

2023-03-08 10:04 UTC, sankaviv1 commented
https://github.com/hmcts/civil-ccd-definition/pull/2322 this is the updated PR that will be merged for this feature

2023-03-19 03:03 UTC, closed without merging