Feat/civ 7646
hmcts/civil-ccd-definition pull request #2467
Opened 2023-04-04 08:54 UTC by bhagyashreesharma90

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-7646

### Change description ###
Changes for bundle trigger api tests

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-04-06 09:35 UTC, filippo-possenti-version1 commented on charts/civil-ccd/values.preview.template.yaml
> +    image: 'hmctspublic.azurecr.io/civil/service:pr-2551'
Marking as "request changes" to prevent this from being merged by mistake.

2023-04-06 09:35 UTC, filippo-possenti-version1 approved these changes

2023-04-06 09:36 UTC, filippo-possenti-version1 requested changes
Marking as "request changes" to prevent the change in values.preview.template.yaml from being merged by mistake.

Approved otherwise.

2023-04-06 12:47 UTC, mounikahmcts submitted a review, later dismissed

2023-04-07 10:46 UTC, filippo-possenti-version1 approved these changes

2023-04-07 13:12 UTC, merged