CIV-10564 transfer online case - screen
hmcts/civil-ccd-definition pull request #3314
Opened 2023-10-02 15:59 UTC by hmcts-version1-ignacio

### [Jira link](https://tools.hmcts.net/jira/browse/CIV-10564) ###
### [Jira link CYA screen](https://tools.hmcts.net/jira/browse/CIV-10565) ###

### Not suitable for SDO for transferring case online ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-10-05 14:27 UTC, maciejmodzelewski submitted a review, later dismissed

2023-10-05 14:58 UTC, Azam-Hmcts approved these changes

2023-10-05 15:02 UTC, ShwetaTandel-hmcts requested changes

2023-10-05 15:44 UTC, ShwetaTandel-hmcts approved these changes

2023-10-11 15:30 UTC, bhagyashreesharma90 approved these changes

2023-10-11 15:31 UTC, ShwetaTandel-hmcts approved these changes

2023-10-16 12:20 UTC, closed without merging

2023-10-16 12:20 UTC, Azam-Hmcts commented
The changes of this PR was merged with API test using this PR https://github.com/hmcts/civil-ccd-definition/pull/3339