feat/CIV-208 changed howMuchWasPaid to MoneyGBP
hmcts/civil-ccd-definition pull request #346
Opened 2022-01-05 10:58 UTC by dtortolaV1

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-208

### Change description ###
Change the field "how much was paid" to MoneyGBP instead of Number

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-01-05 13:41 UTC, bhssamray approved these changes

2022-01-05 13:44 UTC, bhssamray requested changes
Please look at Kenneth's highlighted issue on amounts misrepresented on screens

2022-01-07 12:29 UTC, indu2019 approved these changes
approved

2022-01-07 12:36 UTC, kenneth-hmcts approved these changes

2022-01-07 13:52 UTC, bhssamray submitted a review, later dismissed

2022-01-17 09:07 UTC, kenneth-hmcts approved these changes

2022-01-17 12:11 UTC, sampankumar approved these changes

2022-01-19 13:52 UTC, merged