CIV-0000 - add permission to CUI for common components of hearingFee in CUI
hmcts/civil-ccd-definition pull request #3520
Opened 2023-11-08 10:53 UTC by LeonardoPalmeiro

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-7484

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-11-08 10:57 UTC, miguelMolina3691 submitted a review, later dismissed

2023-11-08 11:05 UTC, m-meulendijks-v1 requested changes
These other userRoles should only have read access, wouldn't you say?
Or do they need create/update as well?

2023-11-08 12:15 UTC, LeonardoPalmeiro commented
> These other userRoles should only have read access, wouldn't you say? Or do they need create/update as well?

done I added R as your suggestion

2023-11-08 12:38 UTC, m-meulendijks-v1 submitted a review, later dismissed

2023-11-08 15:12 UTC, miguelMolina3691 submitted a review, later dismissed

2023-11-10 14:24 UTC, dharmendrak approved these changes

2023-11-17 10:12 UTC, dharmendrak approved these changes

2023-11-17 10:14 UTC, m-meulendijks-v1 approved these changes

2023-11-17 11:12 UTC, merged