CIV-14752 Manage stay changes
hmcts/civil-ccd-definition pull request #4877
Opened 2024-09-30 12:10 UTC by kannan-v-hmcts

PR for https://tools.hmcts.net/jira/browse/CIV-14752

2024-10-01 10:29 UTC, ss-evoco requested changes
Can you please merge in Max's PR and then put these changes into the right release files https://github.com/hmcts/civil-ccd-definition/pull/4848/files

2024-10-01 11:16 UTC, kannan-v-hmcts commented
> Can you please merge in Max's PR and then put these changes into the right release files https://github.com/hmcts/civil-ccd-definition/pull/4848/files

@ss-evoco Merged feat/CIV-15204 and changed the base branch of this PR

2024-10-01 15:16 UTC, dharmendrak approved these changes

2024-10-02 09:23 UTC, ss-evoco approved these changes

2024-10-03 08:45 UTC, m-meulendijks-v1 approved these changes

2024-10-08 15:35 UTC, ss-evoco approved these changes

2024-10-08 16:15 UTC, dharmendrak approved these changes

2024-10-09 07:56 UTC, merged