sdd for unespec claims
hmcts/civil-ccd-definition pull request #4946
Opened 2024-10-15 08:23 UTC by laarmada

### JIRA link (if applicable) ###

(https://tools.hmcts.net/jira/browse/CIV-15523)

### Change description ###

Make "Manage documents" available to UNSPEC 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-10-15 12:59 UTC, ss-evoco approved these changes

2024-10-15 13:30 UTC, ss-evoco requested changes

2024-10-15 13:30 UTC, ss-evoco commented on ccd-definition/CaseEvent/User/UserEvents-amendBundle-prod.json
> +    "RetriesTimeoutURLSubmittedEvent": 0
Needs to be turned off in production now.

2024-10-16 13:53 UTC, ss-evoco approved these changes

2024-10-16 13:54 UTC, m-meulendijks-v1 approved these changes

2024-10-18 08:56 UTC, merged